import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Social Feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
    <Header>

    </Header>
   
    <main>
      {/* sidebar */}
      {/* feed */}
      {/* widgets */}

    </main>

    </div>
  )
}
