import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Social-Feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1>Social Feed Build</h1>
    </div>
  )
}
